name: my_meds
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
 
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
shared_preferences: ^2.0.15
url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Thyroid.jpg
    - assets/images/Consult Doctor.jpg
    - assets/images/Heart.jpg
    - assets/images/Bone Health.jpg
    - assets/images/Vitamins.jpg
    - assets/images/Diabetes.jpeg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
