// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0VEgLwOpQZZo9ldaiyThVApk8fGMrAI',
    appId: '1:1065816227268:web:335c6a4edb443d4a40f891',
    messagingSenderId: '1065816227268',
    projectId: 'mymeds-72343',
    authDomain: 'mymeds-72343.firebaseapp.com',
    storageBucket: 'mymeds-72343.firebasestorage.app',
    measurementId: 'G-52T6D7XZ0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh_D22E-1cXOB79LDNo33P-zNtcN99Ni8',
    appId: '1:1065816227268:android:b929334e8875cbef40f891',
    messagingSenderId: '1065816227268',
    projectId: 'mymeds-72343',
    storageBucket: 'mymeds-72343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYh7P3bFSk6Ue2EcDlelw9q08X8lwa2IA',
    appId: '1:1065816227268:ios:5b4d3b5245004a9c40f891',
    messagingSenderId: '1065816227268',
    projectId: 'mymeds-72343',
    storageBucket: 'mymeds-72343.firebasestorage.app',
    iosBundleId: 'com.example.myMeds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYh7P3bFSk6Ue2EcDlelw9q08X8lwa2IA',
    appId: '1:1065816227268:ios:5b4d3b5245004a9c40f891',
    messagingSenderId: '1065816227268',
    projectId: 'mymeds-72343',
    storageBucket: 'mymeds-72343.firebasestorage.app',
    iosBundleId: 'com.example.myMeds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ0VEgLwOpQZZo9ldaiyThVApk8fGMrAI',
    appId: '1:1065816227268:web:0b3e8402aaa500f640f891',
    messagingSenderId: '1065816227268',
    projectId: 'mymeds-72343',
    authDomain: 'mymeds-72343.firebaseapp.com',
    storageBucket: 'mymeds-72343.firebasestorage.app',
    measurementId: 'G-Q5QKL91P6N',
  );
}
